version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          when: on_fail
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name mystack

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy --template-file newinfra.yml --stack-name mystack
      - run: return 1
      - destroy_environment
    
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
