# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  create_infra:
    docker:
     - image: amazon/aws-cli
    steps:
     - run:
         name: creating infra
         command: echo " running infra job resources.yml"
         command: /home/tarun/playground/Resources.yml

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create_infra
