version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["8c:e5:41:de:cb:53:d8:4c:7c:3f:d4:22:b9:ad:ac:95"] # You can get this ID in section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: find location
          command: |
            ls -ltr 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
